INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (1,'D.I. Yogyakarta','Kab. Bantul');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (2,'D.I. Yogyakarta','Kab. Gunung Kidul');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (3,'D.I. Yogyakarta','Kab. Kulon Progo');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (4,'D.I. Yogyakarta','Kab. Sleman');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (5,'D.I. Yogyakarta','Kota Yogyakarta');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (6,'Sumatera Utara','Kab. Asahan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (7,'Sumatera Utara','Kab. Batubara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (8,'Sumatera Utara','Kab. Dairi');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (9,'Sumatera Utara','Kab. Deli Serdang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (10,'Sumatera Utara','Kota Gunung Sitoli');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (11,'Sumatera Utara','Kab. Humbang Hasudutan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (12,'Sumatera Utara','Kab. Karo');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (13,'Sumatera Utara','Kota Binjai');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (14,'Sumatera Utara','Kota Medan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (15,'Sumatera Utara','Kota Tanjung Balai');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (16,'Sumatera Utara','Kab. Labuhan Batu');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (17,'Sumatera Utara','Kab. Labuhan Batu Selatan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (18,'Sumatera Utara','Kab. Labuhan Batu Utara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (19,'Sumatera Utara','Kab. Langkat');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (20,'Sumatera Utara','Kab. Mandailing Natal');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (21,'Sumatera Utara','Kab. Nias');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (22,'Sumatera Utara','Kab. Nias Barat');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (23,'Sumatera Utara','Kab. Nias Selatan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (24,'Sumatera Utara','Kab. Nias Utara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (25,'Sumatera Utara','Kab. Padang Lawas');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (26,'Sumatera Utara','Kab. Padang Lawas Utara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (27,'Sumatera Utara','Kota Padang Sidimpuan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (28,'Sumatera Utara','Kab. Pak Pak Bharat');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (29,'Sumatera Utara','Kota Pematang Siantar');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (30,'Sumatera Utara','Kab. Samosir');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (31,'Sumatera Utara','Kab. Serdang Bedagai');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (32,'Sumatera Utara','Kota Sibolga');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (33,'Sumatera Utara','Kab. Simalungun');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (34,'Sumatera Utara','Kab. Tapanuli Selatan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (35,'Sumatera Utara','Kab. Tapanuli Tengah');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (36,'Sumatera Utara','Kab. Tapanuli Utara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (37,'Sumatera Utara','Kota Tebing Tinggi');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (38,'Sumatera Utara','Kab. Toba Samosir');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (39,'Sumatera Selatan','Kab. Banyuasin');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (40,'Sumatera Selatan','Kab. Banyuasin');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (41,'Sumatera Selatan','Kab. Empat Lawang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (42,'Sumatera Selatan','Kab. Lahat');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (43,'Sumatera Selatan','Kota Lubuk Linggau');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (44,'Sumatera Selatan','Kab. Muara Enim');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (45,'Sumatera Selatan','Kab. Musi Banyu Asin');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (46,'Sumatera Selatan','Kab. Musi Rawas');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (47,'Sumatera Selatan','Kab. Musi Rawas Utara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (48,'Sumatera Selatan','Kab. Ogan Ilir');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (49,'Sumatera Selatan','Kab. Ogan Komering Ilir');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (50,'Sumatera Selatan','Kab. Ogan Komering Ulu');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (51,'Sumatera Selatan','Kab. Ogan Komering Ulu Selatan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (52,'Sumatera Selatan','Kab. Ogan Komering Ulu Timur');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (53,'Sumatera Selatan','Kota Pagar Alam');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (54,'Sumatera Selatan','Kota Palembang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (55,'Sumatera Selatan','Kab. Penukal Abab Lematang Ilir');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (56,'Sumatera Selatan','Kota Prabumulih');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (57,'Sumatera Barat','Kab. Agam');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (58,'Sumatera Barat','Kab. Dharmasraya');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (59,'Sumatera Barat','Kab. Kepulauan Mentawai');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (60,'Sumatera Barat','Kota Bukittinggi');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (61,'Sumatera Barat','Kota Padang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (62,'Sumatera Barat','Kota Padang Panjang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (63,'Sumatera Barat','Kota Pariaman');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (64,'Sumatera Barat','Kota Payakumbuh');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (65,'Sumatera Barat','Kota Sawah Lunto');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (66,'Sumatera Barat','Kota Solok');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (67,'Sumatera Barat','Kab. Lima Puluh Koto');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (68,'Sumatera Barat','Kab. Padang Pariaman');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (69,'Sumatera Barat','Kab. Pasaman');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (70,'Sumatera Barat','Kab. Pasaman Barat');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (71,'Sumatera Barat','Kab. Pesisir Selatan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (72,'Sumatera Barat','Kab. Sijunjung');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (73,'Sumatera Barat','Kab. Solok');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (74,'Sumatera Barat','Kab. Solok Selatan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (75,'Sumatera Barat','Kab. Tanah Datar');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (76,'Sulawesi Utara','Kota Bitung');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (77,'Sulawesi Utara','Kab. Bolaang Mongondaw');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (78,'Sulawesi Utara','Kab. Bolaang Mongondaw Selatan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (79,'Sulawesi Utara','Kab. Bolaang Mongondaw Timur');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (80,'Sulawesi Utara','Kab. Bolaang Mongondow Utara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (81,'Sulawesi Utara','Kab. Kep. Sangihe');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (82,'Sulawesi Utara','Kab. Kepulauan Talaud');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (83,'Sulawesi Utara','Kota Kotamobagu');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (84,'Sulawesi Utara','Kota Manado');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (85,'Sulawesi Utara','Kab. Minahasa');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (86,'Sulawesi Utara','Kab. Minahasa Selatan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (87,'Sulawesi Utara','Kab. Minahasa Tenggara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (88,'Sulawesi Utara','Kab. Minahasa Utara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (89,'Sulawesi Utara','Kab. Kepulauan Sitaro');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (90,'Sulawesi Utara','Kota Tomohon');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (91,'Sulawesi Tenggara','Kota Bau-Bau');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (92,'Sulawesi Tenggara','Kab. Bombana');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (93,'Sulawesi Tenggara','Kab. Buton');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (94,'Sulawesi Tenggara','Kab. Buton Selatan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (95,'Sulawesi Tenggara','Kab. Buton Tengah');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (96,'Sulawesi Tenggara','Kab. Buton Utara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (97,'Sulawesi Tenggara','Kab. Kolaka');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (98,'Sulawesi Tenggara','Kab. Kolaka Timur');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (99,'Sulawesi Tenggara','Kab. Kolaka Utara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (100,'Sulawesi Tenggara','Kab. Konawe');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (101,'Sulawesi Tenggara','Kab. Konawe Kepulauan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (102,'Sulawesi Tenggara','Kab. Konawe Selatan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (103,'Sulawesi Tenggara','Kab. Konawe Utara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (104,'Sulawesi Tenggara','Kota Kendari');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (105,'Sulawesi Tenggara','Kab. Muna Barat');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (106,'Sulawesi Tenggara','Kab. Muna');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (107,'Sulawesi Tenggara','Kab. Wakatobi');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (108,'Sulawesi Tengah','Kab. Banggai');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (109,'Sulawesi Tengah','Kab. Banggai Kepulauan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (110,'Sulawesi Tengah','Kab. Banggai Laut');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (111,'Sulawesi Tengah','Kab. Buol');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (112,'Sulawesi Tengah','Kab. Donggala');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (113,'Sulawesi Tengah','Kota Palu');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (114,'Sulawesi Tengah','Kab. Morowali');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (115,'Sulawesi Tengah','Kab. Morowali Utara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (116,'Sulawesi Tengah','Kab. Parigi Moutong');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (117,'Sulawesi Tengah','Kab. Poso');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (118,'Sulawesi Tengah','Kab. Sigi');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (119,'Sulawesi Tengah','Kab. Tojo Una-una');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (120,'Sulawesi Tengah','Kab. Toli-toli');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (121,'Sulawesi Selatan','Kab. Bantaeng');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (122,'Sulawesi Selatan','Kab. Barru');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (123,'Sulawesi Selatan','Kab. Bone');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (124,'Sulawesi Selatan','Kab. Bulukumba');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (125,'Sulawesi Selatan','Kab. Enrekang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (126,'Sulawesi Selatan','Kab. Gowa');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (127,'Sulawesi Selatan','Kab. Jeneponto');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (128,'Sulawesi Selatan','Kab. Kepulauan Selayar');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (129,'Sulawesi Selatan','Kab. Luwu');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (130,'Sulawesi Selatan','Kab. Luwu Timur');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (131,'Sulawesi Selatan','Kab. Luwu Utara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (132,'Sulawesi Selatan','Kota Makassar');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (133,'Sulawesi Selatan','Kab. Maros');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (134,'Sulawesi Selatan','Kota Palopo');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (135,'Sulawesi Selatan','Kab. Pangkajene Kepulauan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (136,'Sulawesi Selatan','Kota Pare-pare');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (137,'Sulawesi Selatan','Kab. Pinrang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (138,'Sulawesi Selatan','Kab. Sidenreng Rappang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (139,'Sulawesi Selatan','Kab. Sinjai');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (140,'Sulawesi Selatan','Kab. Soppeng');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (141,'Sulawesi Selatan','Kab. Takalar');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (142,'Sulawesi Selatan','Kab. Tana Toraja');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (143,'Sulawesi Selatan','Kab. Toraja Utara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (144,'Sulawesi Selatan','Kab. Wajo');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (145,'Sulawesi Barat','Kab. Majene');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (146,'Sulawesi Barat','Kab. Mamasa');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (147,'Sulawesi Barat','Kab. Mamuju');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (148,'Sulawesi Barat','Kab. Mamuju Tengah');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (149,'Sulawesi Barat','Kab. Mamuju Utara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (150,'Sulawesi Barat','Kab. Polewali Mandar');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (151,'Riau','Kab. Bengkalis');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (152,'Riau','Kota Dumai');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (153,'Riau','Kab. Indragiri Hilir');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (154,'Riau','Kab. Indragiri Hulu');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (155,'Riau','Kab. Kampar');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (156,'Riau','Kab. Kepulauan Meranti');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (157,'Riau','Kab. Kuantan Singingi');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (158,'Riau','Kota Pekanbaru');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (159,'Riau','Kab. Pelalawan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (160,'Riau','Kab. Rokan Hilir');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (161,'Riau','Kab. Rokan Hulu');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (162,'Riau','Kab. Siak');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (163,'Papua Barat','Kab. Fak-Fak');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (164,'Papua Barat','Kab. Kaimana');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (165,'Papua Barat','Kab. Manokwari');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (166,'Papua Barat','Kab. Manokwari Selatan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (167,'Papua Barat','Kab. Maybrat');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (168,'Papua Barat','Kab. Pegunungan Arfak');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (169,'Papua Barat','Kab. Raja Ampat');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (170,'Papua Barat','Kab. Sorong');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (171,'Papua Barat','Kab. Sorong Selatan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (172,'Papua Barat','Kab. Tambrauw');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (173,'Papua Barat','Kab. Teluk Bintuni');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (174,'Papua Barat','Kab. Teluk Wondama');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (175,'Papua Barat','Kota Sorong');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (176,'Papua','Kab. Asmat');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (177,'Papua','Kab. Biak Numfor');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (178,'Papua','Kab. Boven Digoel');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (179,'Papua','Kab. Deiyai');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (180,'Papua','Kab. Dogiyai');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (181,'Papua','Kab. Intan Jaya');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (182,'Papua','Kab. Jaya Wijaya');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (183,'Papua','Kab. Jayapura');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (184,'Papua','Kab. Keerom');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (185,'Papua','Kab. Kepulauan Yapen');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (186,'Papua','Kab. Lanny Jaya');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (187,'Papua','Kab. Mappi');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (188,'Papua','Kab. Memberamo Raya');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (189,'Papua','Kab. Membramo Tengah');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (190,'Papua','Kab. Merauke');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (191,'Papua','Kab. Mimika');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (192,'Papua','Kab. Nabire');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (193,'Papua','Kab. Nduga');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (194,'Papua','Kab. Paniai');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (195,'Papua','Kab. Pegunungan Bintang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (196,'Papua','Kab. Puncak');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (197,'Papua','Kab. Puncak Jaya');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (198,'Papua','Kab. Sarmi');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (199,'Papua','Kab. Tolikara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (200,'Papua','Kab. Waropen');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (201,'Papua','Kab. Yahukimo');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (202,'Papua','Kab. Yalimo');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (203,'Papua','Kota Jayapura');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (204,'Papua','Kab. Supiori');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (205,'Nusa Tenggara Timur','Kab. Alor');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (206,'Nusa Tenggara Timur','Kab. Belu');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (207,'Nusa Tenggara Timur','Kab. Ende');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (208,'Nusa Tenggara Timur','Kab. Flores Timur');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (209,'Nusa Tenggara Timur','Kota Kupang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (210,'Nusa Tenggara Timur','Kab. Kupang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (211,'Nusa Tenggara Timur','Kab. Lembata');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (212,'Nusa Tenggara Timur','Kab. Malaka');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (213,'Nusa Tenggara Timur','Kab. Manggarai');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (214,'Nusa Tenggara Timur','Kab. Manggarai Barat');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (215,'Nusa Tenggara Timur','Kab. Manggarai Timur');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (216,'Nusa Tenggara Timur','Kab. Nagakeo');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (217,'Nusa Tenggara Timur','Kab. Ngada');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (218,'Nusa Tenggara Timur','Kab. Rote-ndao');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (219,'Nusa Tenggara Timur','Kab. Sabu Raijua');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (220,'Nusa Tenggara Timur','Kab. Sikka');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (221,'Nusa Tenggara Timur','Kab. Sumba Barat');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (222,'Nusa Tenggara Timur','Kab. Sumba Barat Daya');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (223,'Nusa Tenggara Timur','Kab. Sumba Tengah');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (224,'Nusa Tenggara Timur','Kab. Sumba Timur');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (225,'Nusa Tenggara Timur','Kab. Timor Tengah Selatan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (226,'Nusa Tenggara Timur','Kab. Timor Tengah Utara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (227,'Nusa Tenggara Barat','Kab. Bima');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (228,'Nusa Tenggara Barat','Kab. Dompu');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (229,'Nusa Tenggara Barat','Kota Bima');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (230,'Nusa Tenggara Barat','Kab. Lombok Barat');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (231,'Nusa Tenggara Barat','Kab. Lombok Tengah');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (232,'Nusa Tenggara Barat','Kab. Lombok Timur');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (233,'Nusa Tenggara Barat','Kab. Lombok Utara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (234,'Nusa Tenggara Barat','Kota Mataram');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (235,'Nusa Tenggara Barat','Kab. Sumbawa');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (236,'Nusa Tenggara Barat','Kab. Sumbawa Barat');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (237,'Maluku Utara','Kab. Halmahera Selatan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (238,'Maluku Utara','Kab. Halmahera Tengah');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (239,'Maluku Utara','Kab. Halmahera Timur');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (240,'Maluku Utara','Kab. Halmahera Utara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (241,'Maluku Utara','Kab. Kepulauan Sula');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (242,'Maluku Utara','Kab. Kepulauan Morotai');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (243,'Maluku Utara','Kab. Pulau Taliabu');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (244,'Maluku Utara','Kota Ternate');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (245,'Maluku Utara','Kota Tidore Kepulauan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (246,'Maluku Utara','Kab. Halmahera Barat');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (247,'Maluku','Kota Ambon');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (248,'Maluku','Kab. Buru');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (249,'Maluku','Kab. Buru Selatan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (250,'Maluku','Kab. Kepulauan Aru');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (251,'Maluku','Kab. Maluku Barat Daya');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (252,'Maluku','Kab. Maluku Tengah');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (253,'Maluku','Kab. Maluku Tenggara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (254,'Maluku','Kab. Maluku Tenggara Barat');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (255,'Maluku','Kab. Seram Bagian Barat');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (256,'Maluku','Kab. Seram Bagian Timur');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (257,'Maluku','Kota Tual');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (258,'Lampung','Kota Bandar Lampung');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (259,'Lampung','Kab. Lampung Barat');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (260,'Lampung','Kab. Lampung Selatan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (261,'Lampung','Kab. Lampung Tengah');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (262,'Lampung','Kab. Lampung Timur');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (263,'Lampung','Kab. Lampung Utara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (264,'Lampung','Kab. Mesuji');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (265,'Lampung','Kota Metro');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (266,'Lampung','Kab. Pesawaran');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (267,'Lampung','Kab. Pesisir Barat');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (268,'Lampung','Kab. Pringsewu');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (269,'Lampung','Kab. Tanggamus');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (270,'Lampung','Kab. Tulang Bawang Barat');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (271,'Lampung','Kab. Tulang Bawang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (272,'Lampung','Kab. Way Kanan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (273,'Kepulauan Riau','Kab. Karimun');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (274,'Kepulauan Riau','Kab. Kepulauan Anambas');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (275,'Kepulauan Riau','Kab. Lingga');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (276,'Kepulauan Riau','Kab. Natuna');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (277,'Kepulauan Riau','Kota Batam');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (278,'Kepulauan Riau','Kab. Bintan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (279,'Kepulauan Riau','Kota Tanjungpinang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (280,'Kalimantan Timur','Kota Balikpapan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (281,'Kalimantan Timur','Kab. Berau');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (282,'Kalimantan Timur','Kota Bontang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (283,'Kalimantan Timur','Kab. Kutai Barat');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (284,'Kalimantan Timur','Kab. Kutai Kartanegara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (285,'Kalimantan Timur','Kab. Kutai Timur');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (286,'Kalimantan Timur','Kab. Mahakam Ulu');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (287,'Kalimantan Timur','Kab. Paser');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (288,'Kalimantan Timur','Kab. Penajam Paser Utara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (289,'Kalimantan Timur','Kota Samarinda');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (290,'Kalimantan Tengah','Kab. Barito Selatan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (291,'Kalimantan Tengah','Kab. Barito Timur');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (292,'Kalimantan Tengah','Kab. Barito Utara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (293,'Kalimantan Tengah','Kab. Gunung Mas');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (294,'Kalimantan Tengah','Kab. Kapuas');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (295,'Kalimantan Tengah','Kab. Katingan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (296,'Kalimantan Tengah','Kab. Kotawaringin Barat');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (297,'Kalimantan Tengah','Kab. Kotawaringin Timur');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (298,'Kalimantan Tengah','Kab. Lamandau');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (299,'Kalimantan Tengah','Kab. Murung Raya');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (300,'Kalimantan Tengah','Kota Palangka Raya');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (301,'Kalimantan Tengah','Kab. Pulang Pisau');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (302,'Kalimantan Tengah','Kab. Seruyan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (303,'Kalimantan Tengah','Kab. Sukamara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (304,'Kalimantan Utara','Kab. Bulungan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (305,'Kalimantan Utara','Kab. Malinau');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (306,'Kalimantan Utara','Kab. Nunukan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (307,'Kalimantan Utara','Kab. Tanah Tidung');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (308,'Kalimantan Utara','Kota Tarakan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (309,'Kalimantan Selatan','Kab. Balangan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (310,'Kalimantan Selatan','Kab. Banjar');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (311,'Kalimantan Selatan','Kota Banjarbaru');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (312,'Kalimantan Selatan','Kota Banjarmasin');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (313,'Kalimantan Selatan','Kab. Barito Kuala');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (314,'Kalimantan Selatan','Kab. Hulu Sungai Selatan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (315,'Kalimantan Selatan','Kab. Hulu Sungai Tengah');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (316,'Kalimantan Selatan','Kab. Hulu Sungai Utara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (317,'Kalimantan Selatan','Kab. Kota Baru');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (318,'Kalimantan Selatan','Kab. Tabalong');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (319,'Kalimantan Selatan','Kab. Tanah Bumbu');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (320,'Kalimantan Selatan','Kab. Tanah Laut');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (321,'Kalimantan Selatan','Kab. Tapin');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (322,'Kalimantan Barat','Kab. Bengkayang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (323,'Kalimantan Barat','Kab. Kapuas Hulu');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (324,'Kalimantan Barat','Kab. Kayong Utara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (325,'Kalimantan Barat','Kab. Ketapang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (326,'Kalimantan Barat','Kab. Kuburaya');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (327,'Kalimantan Barat','Kab. Landak');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (328,'Kalimantan Barat','Kab. Melawi');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (329,'Kalimantan Barat','Kab. Mempawah');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (330,'Kalimantan Barat','Kab. Sambas');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (331,'Kalimantan Barat','Kab. Sanggau');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (332,'Kalimantan Barat','Kab. Sekadau');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (333,'Kalimantan Barat','Kab. Sintang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (334,'Kalimantan Barat','Kota Pontianak');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (335,'Kalimantan Barat','Kota Singkawang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (336,'Jawa Timur','Kab. Bangkalan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (337,'Jawa Timur','Kab. Banyuwangi');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (338,'Jawa Timur','Kab. Blitar');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (339,'Jawa Timur','Kab. Bojonegoro');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (340,'Jawa Timur','Kab. Bondowoso');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (341,'Jawa Timur','Kab. Gresik');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (342,'Jawa Timur','Kab. Jember');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (343,'Jawa Timur','Kab. Jombang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (344,'Jawa Timur','Kab. Kediri');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (345,'Jawa Timur','Kab. Lamongan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (346,'Jawa Timur','Kab. Lumajang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (347,'Jawa Timur','Kab. Madiun');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (348,'Jawa Timur','Kab. Magetan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (349,'Jawa Timur','Kab. Malang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (350,'Jawa Timur','Kab. Mojokerto');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (351,'Jawa Timur','Kab. Nganjuk');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (352,'Jawa Timur','Kab. Ngawi');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (353,'Jawa Timur','Kab. Pacitan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (354,'Jawa Timur','Kab. Pamekasan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (355,'Jawa Timur','Kab. Pasuruan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (356,'Jawa Timur','Kab. Ponorogo');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (357,'Jawa Timur','Kab. Probolinggo');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (358,'Jawa Timur','Kab. Sampang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (359,'Jawa Timur','Kab. Sidoarjo');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (360,'Jawa Timur','Kab. Situbondo');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (361,'Jawa Timur','Kab. Sumenep');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (362,'Jawa Timur','Kab. Trenggalek');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (363,'Jawa Timur','Kab. Tuban');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (364,'Jawa Timur','Kab. Tulungagung');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (365,'Jawa Timur','Kota Batu');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (366,'Jawa Timur','Kota Blitar');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (367,'Jawa Timur','Kota Kediri');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (368,'Jawa Timur','Kota Madiun');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (369,'Jawa Timur','Kota Malang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (370,'Jawa Timur','Kota Mojokerto');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (371,'Jawa Timur','Kota Pasuruan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (372,'Jawa Timur','Kota Probolinggo');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (373,'Jawa Timur','Kota Surabaya');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (374,'Jawa Tengah','Kab. Banjarnegara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (375,'Jawa Tengah','Kab. Banyumas');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (376,'Jawa Tengah','Kab. Batang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (377,'Jawa Tengah','Kab. Blora');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (378,'Jawa Tengah','Kab. Boyolali');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (379,'Jawa Tengah','Kab. Brebes');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (380,'Jawa Tengah','Kab. Cilacap');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (381,'Jawa Tengah','Kab. Demak');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (382,'Jawa Tengah','Kab. Grobogan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (383,'Jawa Tengah','Kab. Jepara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (384,'Jawa Tengah','Kab. Karanganyar');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (385,'Jawa Tengah','Kab. Kebumen');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (386,'Jawa Tengah','Kab. Kendal');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (387,'Jawa Tengah','Kab. Klaten');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (388,'Jawa Tengah','Kab. Kudus');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (389,'Jawa Tengah','Kab. Magelang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (390,'Jawa Tengah','Kab. Pati');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (391,'Jawa Tengah','Kab. Pekalongan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (392,'Jawa Tengah','Kab. Pemalang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (393,'Jawa Tengah','Kab. Purbalingga');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (394,'Jawa Tengah','Kab. Purworejo');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (395,'Jawa Tengah','Kab. Rembang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (396,'Jawa Tengah','Kab. Semarang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (397,'Jawa Tengah','Kab. Sragen');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (398,'Jawa Tengah','Kab. Sukoharjo');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (399,'Jawa Tengah','Kab. Tegal');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (400,'Jawa Tengah','Kab. Temanggung');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (401,'Jawa Tengah','Kab. Wonogiri');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (402,'Jawa Tengah','Kab. Wonosobo');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (403,'Jawa Tengah','Kota Magelang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (404,'Jawa Tengah','Kota Pekalongan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (405,'Jawa Tengah','Kota Salatiga');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (406,'Jawa Tengah','Kota Semarang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (407,'Jawa Tengah','Kota Surakarta');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (408,'Jawa Tengah','Kota Tegal');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (409,'Jambi','Kab. Batang Hari');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (410,'Jambi','Kab. Bungo');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (411,'Jambi','Kab. Sarolangun');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (412,'Jambi','Kab. Merangin');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (413,'Jambi','Kab. Muaro Jambi');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (414,'Jambi','Kab. Kerinci');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (415,'Jambi','Kab. Tanjung Jabung Barat');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (416,'Jambi','Kab. Tanjung Jabung Timur');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (417,'Jambi','Kab. Tebo');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (418,'Jambi','Kota Jambi');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (419,'Jambi','Kota Sungai Penuh');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (420,'D.K.I. Jakarta','Kab. Kepulauan Seribu');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (421,'D.K.I. Jakarta','Kota Jakarta Barat');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (422,'D.K.I. Jakarta','Kota Jakarta Pusat');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (423,'D.K.I. Jakarta','Kota Jakarta Selatan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (424,'D.K.I. Jakarta','Kota Jakarta Timur');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (425,'D.K.I. Jakarta','Kota Jakarta Utara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (426,'Jawa Barat','Kab. Bogor');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (427,'Jawa Barat','Kab. Bandung');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (428,'Jawa Barat','Kab. Bandung Barat');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (429,'Jawa Barat','Kab. Bekasi');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (430,'Jawa Barat','Kab. Ciamis');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (431,'Jawa Barat','Kab. Cianjur');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (432,'Jawa Barat','Kab. Cirebon');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (433,'Jawa Barat','Kab. Garut');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (434,'Jawa Barat','Kab. Indramayu');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (435,'Jawa Barat','Kab. Karawang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (436,'Jawa Barat','Kab. Kuningan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (437,'Jawa Barat','Kab. Majalengka');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (438,'Jawa Barat','Kab. Pangandaran');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (439,'Jawa Barat','Kab. Purwakarta');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (440,'Jawa Barat','Kab. Subang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (441,'Jawa Barat','Kab. Sukabumi');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (442,'Jawa Barat','Kab. Sumedang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (443,'Jawa Barat','Kab. Tasikmalaya');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (444,'Jawa Barat','Kota Bandung');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (445,'Jawa Barat','Kota Banjar');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (446,'Jawa Barat','Kota Bekasi');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (447,'Jawa Barat','Kota Bogor');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (448,'Jawa Barat','Kota Cimahi');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (449,'Jawa Barat','Kota Cirebon');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (450,'Jawa Barat','Kota Depok');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (451,'Jawa Barat','Kota Sukabumi');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (452,'Jawa Barat','Kota Tasikmalaya');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (453,'Gorontalo','Kab. Boalemo');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (454,'Gorontalo','Kab. Bone Bolango');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (455,'Gorontalo','Kab. Gorontalo');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (456,'Gorontalo','Kab. Gorontalo Utara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (457,'Gorontalo','Kota Gorontalo');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (458,'Gorontalo','Kab. Pohuwato');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (459,'Bengkulu','Kota Bengkulu');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (460,'Bengkulu','Kab. Bengkulu Selatan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (461,'Bengkulu','Kab. Bengkulu Tengah');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (462,'Bengkulu','Kab. Bengkulu Utara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (463,'Bengkulu','Kab. Kaur');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (464,'Bengkulu','Kab. Kepahiang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (465,'Bengkulu','Kab. Lebong');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (466,'Bengkulu','Kab. Muko-muko');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (467,'Bengkulu','Kab. Rejang Lebong');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (468,'Bengkulu','Kab. Seluma');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (469,'Banten','Kab. Lebak');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (470,'Banten','Kab. Pandeglang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (471,'Banten','Kab. Serang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (472,'Banten','Kab. Tangerang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (473,'Banten','Kota Cilegon');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (474,'Banten','Kota Serang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (475,'Banten','Kota Tangerang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (476,'Banten','Kota Tangerang Selatan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (477,'Bali','Kab. Badung');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (478,'Bali','Kab. Bangli');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (479,'Bali','Kab. Buleleng');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (480,'Bali','Kab. Gianyar');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (481,'Bali','Kab. Jembrana');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (482,'Bali','Kab. Karang Asem');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (483,'Bali','Kab. Klungkung');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (484,'Bali','Kab. Tabanan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (485,'Bali','Kota Denpasar');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (486,'Bangka Belitung','Kab. Bangka');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (487,'Bangka Belitung','Kab. Bangka Barat');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (488,'Bangka Belitung','Kab. Bangka Selatan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (489,'Bangka Belitung','Kab. Belitung');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (490,'Bangka Belitung','Kab. Belitung Timur');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (491,'Bangka Belitung','Kota Pangkalpinang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (492,'Bangka Belitung','Kab. Bangka Tengah');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (493,'Aceh','Kab. Aceh Barat');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (494,'Aceh','Kab. Aceh Barat Daya');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (495,'Aceh','Kab. Aceh Besar');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (496,'Aceh','Kab. Aceh Jaya');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (497,'Aceh','Kab. Aceh Selatan');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (498,'Aceh','Kab. Aceh Singkil');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (499,'Aceh','Kab. Aceh Tamiang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (500,'Aceh','Kab. Aceh Tengah');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (501,'Aceh','Kab. Aceh Tenggara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (502,'Aceh','Kab. Aceh Timur');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (503,'Aceh','Kab. Aceh Utara');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (504,'Aceh','Kota Banda Aceh');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (505,'Aceh','Kab. Bener Meriah');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (506,'Aceh','Kab. Bireuen');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (507,'Aceh','Kab. Gayo Lues');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (508,'Aceh','Kota Langsa');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (509,'Aceh','Kota Lhokseumawe');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (510,'Aceh','Kab. Nagan Raya');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (511,'Aceh','Kab. Pidie');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (512,'Aceh','Kab. Pidie Jaya');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (513,'Aceh','Kota Sabang');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (514,'Aceh','Kab. Simeulue');
INSERT INTO `locations` (`id`,`provinsi`,`kotakabupaten`) VALUES (515,'Aceh','Kota Subulussalam');